// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ZMsgh4Z0usY5IlAn6z5JqzbTwQg9mC0',
    appId: '1:852490597256:web:0eb8cbffc2c9b5efe8803d',
    messagingSenderId: '852490597256',
    projectId: 'oasis-c63eb',
    authDomain: 'oasis-c63eb.firebaseapp.com',
    storageBucket: 'oasis-c63eb.appspot.com',
    measurementId: 'G-L76DHHGZSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ1wqjPrZZ2ywsKVdWOe8KeMpdaHFcQ2c',
    appId: '1:852490597256:android:b14442f75ba60673e8803d',
    messagingSenderId: '852490597256',
    projectId: 'oasis-c63eb',
    storageBucket: 'oasis-c63eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkjkZjSqScLry7UU5bbBeNHs3LJ70PL8A',
    appId: '1:852490597256:ios:cb8fda3d87941300e8803d',
    messagingSenderId: '852490597256',
    projectId: 'oasis-c63eb',
    storageBucket: 'oasis-c63eb.appspot.com',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkjkZjSqScLry7UU5bbBeNHs3LJ70PL8A',
    appId: '1:852490597256:ios:cb8fda3d87941300e8803d',
    messagingSenderId: '852490597256',
    projectId: 'oasis-c63eb',
    storageBucket: 'oasis-c63eb.appspot.com',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2ZMsgh4Z0usY5IlAn6z5JqzbTwQg9mC0',
    appId: '1:852490597256:web:31961ed14c57c621e8803d',
    messagingSenderId: '852490597256',
    projectId: 'oasis-c63eb',
    authDomain: 'oasis-c63eb.firebaseapp.com',
    storageBucket: 'oasis-c63eb.appspot.com',
    measurementId: 'G-S0JNBEZGT4',
  );
}
